version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elk_es01
    restart: on-failure
    volumes:
      - ../.docker/es01:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elastic

networks:
  elastic:
    external: true